routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Auth::routes();
//
//Route::group(['middleware' => ['auth']], function () {
//
//    Route::redirect('/home', '/', 301);
//
//    Route::get('/', 'WarehouseController@index')->name('home');
//
//    Route::post('confirm', 'WarehouseController@confirm');
//    Route::post('import', 'WarehouseController@import');
//    Route::get('import-delete/{id}', 'WarehouseController@deleteImport');
//
//    Route::post('warehouse-add', 'WarehouseController@warehouseAdd');
//
//    Route::get('export', 'ProductController@export');
//    Route::get('export-details/{id}', 'ProductController@exportDetails');
//
//    Route::post('product-update', 'ProductController@productUpdate');
//    Route::post('product-add', 'ProductController@productAdd');
//
//    Route::get('product-details/{id}', 'ProductController@productDetails');
//    Route::get('history-import', 'WarehouseController@historyImport');
//
//});


Auth::routes();

Route::redirect('/home', '/', 301);

Route::get('/', 'HomeController@index')->name('home');

Route::group(['middleware' => 'auth'], function () {
	Route::resource('user', 'UserController', ['except' => ['show']]);
	Route::get('profile', ['as' => 'profile.edit', 'uses' => 'ProfileController@edit']);
	Route::put('profile', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);

    Route::get('delete-user/{id}', ['as' => 'profile.delete-user', 'uses' => 'ProfileController@delete']);

    Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'ProfileController@password']);
    Route::get('add', ['as' => 'profile.add', 'uses' => 'ProfileController@add']);
    Route::put('add', ['as' => 'profile.store', 'uses' => 'ProfileController@store']);

    Route::get('import', ['as' => 'import.data', 'uses' => 'WarehouseController@indexImport']);
    Route::post('confirm', ['as' => 'import.confirm', 'uses' => 'WarehouseController@confirm']);
    Route::post('store', ['as' => 'import.store', 'uses' => 'WarehouseController@import']);
    Route::post('warehouse-add', ['as' => 'import.warehouse-add', 'uses' => 'WarehouseController@warehouseAdd']);
    Route::get('import-delete/{id}', ['as' => 'import.delete', 'uses' => 'WarehouseController@deleteImport']);
    Route::get('imported-data', ['as' => 'import.history', 'uses' => 'WarehouseController@historyImport']);
    Route::get('imported-last', ['as' => 'import.last', 'uses' => 'WarehouseController@lastImport']);

    Route::get('warehouse', ['as' => 'warehouse', 'uses' => 'WarehouseController@index']);

    Route::get('blank', ['as' => 'blank', 'uses' => 'BlankController@index']);
    Route::get('blank-add', ['as' => 'blank.add', 'uses' => 'BlankController@add']);
    Route::get('blank-edit/{id}', ['as' => 'blank.add', 'uses' => 'BlankController@edit']);
    Route::put('blank-add', ['as' => 'blank.add', 'uses' => 'BlankController@blankSubmit']);
    Route::get('blank-details', ['as' => 'blank.details', 'uses' => 'BlankController@blankDetails']);
    Route::post('blank-update', ['as' => 'blank.update', 'uses' => 'BlankController@blankUpdate']);
    Route::post('ajax-blank-product', ['as' => 'blank.product', 'uses' => 'BlankController@blankProductUpdate']);
    Route::get('blank-delete/{id}', ['as' => 'blank.delete', 'uses' => 'BlankController@blankDelete']);

    Route::get('products', ['as' => 'product.all', 'uses' => 'WarehouseController@index']);
    Route::get('product-details/{id}', ['as' => 'product.details', 'uses' => 'ProductController@productDetails']);
    Route::get('export-details/{id}', ['as' => 'product.export', 'uses' => 'ProductController@exportDetails']);
    Route::put('product-add', ['as' => 'product.add', 'uses' => 'ProductController@productAdd']);
    Route::get('product-add', ['as' => 'product.add', 'uses' => 'ProductController@productAddIndex']);
    Route::post('product-update', ['as' => 'product.update', 'uses' => 'ProductController@productUpdate']);
    Route::get('product-delete/{id}', ['as' => 'product.delete', 'uses' => 'ProductController@productDelete']);


});

resources/views/layouts/navbars/navbar.blade.php
@auth()
    @include('layouts.navbars.navs.auth')
@endauth
    
@guest()
    @include('layouts.navbars.navs.guest')
@endguest

resources/views/layouts/navbars/sidebar.blade.php
<nav class="navbar navbar-vertical fixed-left navbar-expand-md navbar-light bg-white" id="sidenav-main">
    <div class="container-fluid">
        <!-- Toggler -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#sidenav-collapse-main" aria-controls="sidenav-main" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <!-- Brand -->
        <a class="navbar-brand pt-0" href="{{ route('home') }}">
            <img src="{{ secure_asset('argon') }}/img/theme/team-0-800x800.jpg" class="navbar-brand-img" alt="...">
        </a>
        <!-- User -->
        <ul class="nav align-items-center d-md-none">
            <li class="nav-item dropdown">
                <a class="nav-link" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <div class="media align-items-center">
                        <span class="avatar avatar-sm rounded-circle">
                        <img alt="Image placeholder" src="{{ secure_asset('argon') }}/img/theme/team-1-800x800.jpg">
                        </span>
                    </div>
                </a>
                <div class="dropdown-menu dropdown-menu-arrow dropdown-menu-right">
                    <div class=" dropdown-header noti-title">
                        <h6 class="text-overflow m-0">{{ __('Welcome!') }}</h6>
                    </div>
                    <a href="{{ route('profile.edit') }}" class="dropdown-item">
                        <i class="ni ni-single-02"></i>
                        <span>{{ __('My profile') }}</span>
                    </a>
                    <a href="#" class="dropdown-item">
                        <i class="ni ni-settings-gear-65"></i>
                        <span>{{ __('Settings') }}</span>
                    </a>
                    <a href="#" class="dropdown-item">
                        <i class="ni ni-calendar-grid-58"></i>
                        <span>{{ __('Activity') }}</span>
                    </a>
                    <a href="#" class="dropdown-item">
                        <i class="ni ni-support-16"></i>
                        <span>{{ __('Support') }}</span>
                    </a>
                    <div class="dropdown-divider"></div>
                    <a href="{{ route('logout') }}" class="dropdown-item" onclick="event.preventDefault();
                    document.getElementById('logout-form').submit();">
                        <i class="ni ni-user-run"></i>
                        <span>{{ __('Logout') }}</span>
                    </a>
                </div>
            </li>
        </ul>
        <!-- Collapse -->
        <div class="collapse navbar-collapse" id="sidenav-collapse-main">
            <!-- Collapse header -->
            <div class="navbar-collapse-header d-md-none">
                <div class="row">
                    <div class="col-6 collapse-brand">
                        <a href="{{ route('home') }}">
                            <img src="{{ secure_asset('argon') }}/img/theme/team-0-800x800.jpg">
                        </a>
                    </div>
                    <div class="col-6 collapse-close">
                        <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#sidenav-collapse-main" aria-controls="sidenav-main" aria-expanded="false" aria-label="Toggle sidenav">
                            <span></span>
                            <span></span>
                        </button>
                    </div>
                </div>
            </div>
            <!-- Form -->
            <form class="mt-4 mb-3 d-md-none">
                <div class="input-group input-group-rounded input-group-merge">
                    <input type="search" class="form-control form-control-rounded form-control-prepended" placeholder="{{ __('Search') }}" aria-label="Search">
                    <div class="input-group-prepend">
                        <div class="input-group-text">
                            <span class="fa fa-search"></span>
                        </div>
                    </div>
                </div>
            </form>
            <!-- Navigation -->
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('home') }}">
                        <i class="ni ni-tv-2 text-primary"></i> {{ __('Dashboard') }}
                    </a>
                </li>
                <li class="nav-item @if(Request::is('import')) active @endif">
                    <a class="nav-link" href="{{route('import.data')}}">
                        <i class="fa fa-info text-blue"></i> {{ __('Import Area') }}
                    </a>
                </li>
                <li class="nav-item @if(Request::is(['warehouse', 'product-add'])) active @endif">
                    <a class="nav-link" href="#navbar-1" data-toggle="collapse" role="button" aria-expanded="true" aria-controls="navbar-1">
                        <i class="fa fa-inbox text-orange"></i>
                        <span class="nav-link-text">{{ __('Products') }}</span>
                    </a>

                    <div class="collapse" id="navbar-1">
                        <ul class="nav nav-sm flex-column">
                            <li class="nav-item @if(Request::is(['warehouse'])) active @endif">
                                <a class="nav-link" href="{{route('warehouse')}}">
                                    {{ __('Product Management') }}
                                </a>
                            </li>
                            <li class="nav-item @if(Request::is(['product-add'])) active @endif">
                                <a class="nav-link" href="{{ route('product.add') }}">
                                    {{ __('Add a new Product') }}
                                </a>
                            </li>
                        </ul>
                    </div>
                </li>
                <li class="nav-item @if(Request::is(['blank', 'blank-add'])) active @endif">
                    <a class="nav-link" href="#navbar-3" data-toggle="collapse" role="button" aria-expanded="true" aria-controls="navbar-3">
                        <i class="fa fa-tasks"></i>
                        <span class="nav-link-text">{{ __('Blanks') }}</span>
                    </a>

                    <div class="collapse" id="navbar-3">
                        <ul class="nav nav-sm flex-column @if(Request::is(['blank'])) active @endif">
                            <li class="nav-item">
                                <a class="nav-link" href="{{route('blank')}}">
                                    {{ __('Blank Management') }}
                                </a>
                            </li>
                            <li class="nav-item @if(Request::is(['blank-add'])) active @endif">
                                <a class="nav-link" href="{{ route('blank.add') }}">
                                    {{ __('Add a new Blank') }}
                                </a>
                            </li>
                        </ul>
                    </div>
                </li>
                <li class="nav-item @if(Request::is(['imported-last'])) active @endif">
                    <a class="nav-link" href="{{route('import.last')}}">
                        <i class="fa fa-database text-yellow"></i> {{ __('Last In/Out') }}
                    </a>
                </li>
                <li class="nav-item @if(Request::is(['imported-data'])) active @endif">
                    <a class="nav-link" href="{{route('import.history')}}">
                        <i class="fa fa-file-import text-green"></i> {{ __('Imported Data') }}
                    </a>
                </li>
                <li class="nav-item @if(Request::is(['profile', 'add', 'user'])) active @endif">
                    <a class="nav-link" href="#navbar-2" data-toggle="collapse" role="button" aria-expanded="true" aria-controls="navbar-2">
                        <i class="fab fa-laravel" style="color: #f4645f;"></i>
                        <span class="nav-link-text" style="color: #f4645f;">{{ __('Users') }}</span>
                    </a>

                    <div class="collapse" id="navbar-2">
                        <ul class="nav nav-sm flex-column @if(Request::is(['profile'])) active @endif">
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('profile.edit') }}">
                                    {{ __('User profile') }}
                                </a>
                            </li>
                            <li class="nav-item @if(Request::is(['add'])) active @endif">
                                <a class="nav-link" href="{{ route('profile.add') }}">
                                    {{ __('Add a new User') }}
                                </a>
                            </li>
                            <li class="nav-item @if(Request::is(['user'])) active @endif">
                                <a class="nav-link" href="{{ route('user.index') }}">
                                    {{ __('User Management') }}
                                </a>
                            </li>
                        </ul>
                    </div>
                </li>
            </ul>
            <!-- Divider -->
            <hr class="my-3">
            <!-- Heading -->
            <h6 class="navbar-heading text-muted">Documentation</h6>
            <!-- Navigation -->
            <ul class="navbar-nav mb-md-3">
                <li class="nav-item">
                    <a class="nav-link" href="https://demos.creative-tim.com/argon-dashboard/docs/getting-started/overview.html">
                        <i class="ni ni-spaceship"></i> Getting started
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="https://demos.creative-tim.com/argon-dashboard/docs/foundation/colors.html">
                        <i class="ni ni-palette"></i> Foundation
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="https://demos.creative-tim.com/argon-dashboard/docs/components/alerts.html">
                        <i class="ni ni-ui-04"></i> Components
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>